# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentGate < Formula
  desc "Single-user audit gate for AI agent HTTPS traffic"
  homepage "https://github.com/WZ/agent-gate"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.1/agent-gate_0.3.1_darwin_x86_64.tar.gz"
      sha256 "c6893d957b8272a49858c0deb3013d3965e1c237ad1f038d553f6a5005e87b4c"

      define_method(:install) do
        bin.install "agent-gate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.1/agent-gate_0.3.1_darwin_arm64.tar.gz"
      sha256 "2c2619ab9e20029db850713d92d8d88ecdd5c6738661e36d555a07269face952"

      define_method(:install) do
        bin.install "agent-gate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.1/agent-gate_0.3.1_linux_x86_64.tar.gz"
      sha256 "455871e9a38938282403a48719c45d084398fb8f50953206b123226067413f01"
      define_method(:install) do
        bin.install "agent-gate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.1/agent-gate_0.3.1_linux_arm64.tar.gz"
      sha256 "07f96dab875ce56a3c32892e33e82bebb5e0cf4181cf99001402f8e41b038a73"
      define_method(:install) do
        bin.install "agent-gate"
      end
    end
  end

  test do
    system "#{bin}/agent-gate", "version"
  end
end
