# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentGate < Formula
  desc "Single-user audit gate for AI agent HTTPS traffic"
  homepage "https://github.com/WZ/agent-gate"
  version "0.3.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.4/agent-gate_0.3.4_darwin_x86_64.tar.gz"
      sha256 "5badda56c179be8a411831f4bb344628ef4c107cc5dfff8834f99e1312b042e3"

      define_method(:install) do
        bin.install "agent-gate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.4/agent-gate_0.3.4_darwin_arm64.tar.gz"
      sha256 "5de584e77f177ddc502bef7de00d14e7a4f0d75f459d5dfc4aa078747ad38fd5"

      define_method(:install) do
        bin.install "agent-gate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.4/agent-gate_0.3.4_linux_x86_64.tar.gz"
      sha256 "b78fa2cbb385e18119f96d6c99f1b461de9f06545dee79309294e084d5505bf8"
      define_method(:install) do
        bin.install "agent-gate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/WZ/agent-gate/releases/download/v0.3.4/agent-gate_0.3.4_linux_arm64.tar.gz"
      sha256 "8f4448bd4d13a9f12423664a622d20904a1eb181c3f518fdc705c4f5d1686aad"
      define_method(:install) do
        bin.install "agent-gate"
      end
    end
  end

  test do
    system "#{bin}/agent-gate", "version"
  end
end
